import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsOfService() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      <Card className="w-full max-w-2xl">
        <CardHeader>
          <CardTitle className="text-2xl text-center">
            Terms of Service
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm text-foreground">
          <p>
            Welcome to SmartChat AI! By using our service, you agree to the
            following terms:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must be at least 13 years old to use this service.</li>
            <li>
              Do not use SmartChat AI for any unlawful, harmful, or abusive
              activities.
            </li>
            <li>
              We reserve the right to suspend or terminate accounts that violate
              our terms.
            </li>
            <li>
              All content generated by SmartChat AI is for informational
              purposes only and should not be considered professional advice.
            </li>
            <li>
              We may update these terms at any time. Continued use of the
              service means you accept the new terms.
            </li>
            <li>
              You are responsible for maintaining the confidentiality of your
              account credentials.
            </li>
            <li>
              SmartChat AI is provided "as is" without warranties of any kind.
            </li>
          </ul>
          <p>For questions, contact us at support@smartchatai.com.</p>
        </CardContent>
      </Card>
    </div>
  );
}
